### ISSUE TITLE
Allow .json in filename of a form

### ISSUE THREAD

**Issue by philwareham** [NicolasGraph/oui_flat#2]
Hi Nicholas,

I need to have a form within the new Textpattern.com website with 'rah_eo_version.json' as the form name, that form is then [output by rah_external as a JSON file](https://github.com/gocom/rah_external_output#content-types-and-file-extensions).

So I would need to label it either as follows:

1. `forms/rah_eo_version.json.misc.txp`, or
2. `forms/misc/rah_eo_version.json.txp`

Currently I can't do that with out_flat as it seems to have a problem with the `.json` part of the name, which gets removed on import. The plugin ideally needs to be able to recognise and deal with this filename convention (and probably the other filenames allowed for rah_external in my link reference above).

Probably needs to be considered for the theme branch work in Textpattern core too.

**Comment by NicolasGraph** [comment]
Ok @philwareham, I didn't see that; I'll take a look next week.
Good to know for the core too…

**Comment by NicolasGraph** [comment]
Sorry @philwareham, as you know, I worked to fix that in the Textpattern _themes_ branch but I didn't patch the plugin. As I told for the core, fixing this issue would require the plugin users to use form subfolders, introducing a consistency issue for some people. As the pugin will need a complete rewrite to support the upcomming 'skin' related features, I think I won't patch the current version.

**Comment by philwareham** [comment]
Hey! No problem. If this works on the themes branch that would be my preferred option anyway.
